# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: word_count.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'word_count.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10word_count.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x7f\n\x11WordCountResponse\x12\x37\n\x0bword_counts\x18\x01 \x03(\x0b\x32\".WordCountResponse.WordCountsEntry\x1a\x31\n\x0fWordCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"7\n\x18MostFrequentWordResponse\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\x7f\n\x10WordCountService\x12.\n\nCountWords\x12\x0c.TextRequest\x1a\x12.WordCountResponse\x12;\n\x10MostFrequentWord\x12\x0c.TextRequest\x1a\x19.MostFrequentWordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word_count_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORDCOUNTRESPONSE_WORDCOUNTSENTRY']._loaded_options = None
  _globals['_WORDCOUNTRESPONSE_WORDCOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_TEXTREQUEST']._serialized_start=20
  _globals['_TEXTREQUEST']._serialized_end=47
  _globals['_WORDCOUNTRESPONSE']._serialized_start=49
  _globals['_WORDCOUNTRESPONSE']._serialized_end=176
  _globals['_WORDCOUNTRESPONSE_WORDCOUNTSENTRY']._serialized_start=127
  _globals['_WORDCOUNTRESPONSE_WORDCOUNTSENTRY']._serialized_end=176
  _globals['_MOSTFREQUENTWORDRESPONSE']._serialized_start=178
  _globals['_MOSTFREQUENTWORDRESPONSE']._serialized_end=233
  _globals['_WORDCOUNTSERVICE']._serialized_start=235
  _globals['_WORDCOUNTSERVICE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
