// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/wordcount.proto

package wordcountpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_proto_wordcount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wordcount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_proto_wordcount_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type WordCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WordCounts    map[string]int32       `protobuf:"bytes,1,rep,name=word_counts,json=wordCounts,proto3" json:"word_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCountResponse) Reset() {
	*x = WordCountResponse{}
	mi := &file_proto_wordcount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCountResponse) ProtoMessage() {}

func (x *WordCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wordcount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCountResponse.ProtoReflect.Descriptor instead.
func (*WordCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_wordcount_proto_rawDescGZIP(), []int{1}
}

func (x *WordCountResponse) GetWordCounts() map[string]int32 {
	if x != nil {
		return x.WordCounts
	}
	return nil
}

var File_proto_wordcount_proto protoreflect.FileDescriptor

const file_proto_wordcount_proto_rawDesc = "" +
	"\n" +
	"\x15proto/wordcount.proto\"!\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x97\x01\n" +
	"\x11WordCountResponse\x12C\n" +
	"\vword_counts\x18\x01 \x03(\v2\".WordCountResponse.WordCountsEntryR\n" +
	"wordCounts\x1a=\n" +
	"\x0fWordCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012B\n" +
	"\x10WordCountService\x12.\n" +
	"\n" +
	"CountWords\x12\f.TextRequest\x1a\x12.WordCountResponseB\x1bZ\x19./wordcountpb;wordcountpbb\x06proto3"

var (
	file_proto_wordcount_proto_rawDescOnce sync.Once
	file_proto_wordcount_proto_rawDescData []byte
)

func file_proto_wordcount_proto_rawDescGZIP() []byte {
	file_proto_wordcount_proto_rawDescOnce.Do(func() {
		file_proto_wordcount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wordcount_proto_rawDesc), len(file_proto_wordcount_proto_rawDesc)))
	})
	return file_proto_wordcount_proto_rawDescData
}

var file_proto_wordcount_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wordcount_proto_goTypes = []any{
	(*TextRequest)(nil),       // 0: TextRequest
	(*WordCountResponse)(nil), // 1: WordCountResponse
	nil,                       // 2: WordCountResponse.WordCountsEntry
}
var file_proto_wordcount_proto_depIdxs = []int32{
	2, // 0: WordCountResponse.word_counts:type_name -> WordCountResponse.WordCountsEntry
	0, // 1: WordCountService.CountWords:input_type -> TextRequest
	1, // 2: WordCountService.CountWords:output_type -> WordCountResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_wordcount_proto_init() }
func file_proto_wordcount_proto_init() {
	if File_proto_wordcount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wordcount_proto_rawDesc), len(file_proto_wordcount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wordcount_proto_goTypes,
		DependencyIndexes: file_proto_wordcount_proto_depIdxs,
		MessageInfos:      file_proto_wordcount_proto_msgTypes,
	}.Build()
	File_proto_wordcount_proto = out.File
	file_proto_wordcount_proto_goTypes = nil
	file_proto_wordcount_proto_depIdxs = nil
}
