// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/wordcount.proto

package wordcountpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WordCountService_CountWords_FullMethodName = "/WordCountService/CountWords"
)

// WordCountServiceClient is the client API for WordCountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WordCountServiceClient interface {
	CountWords(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*WordCountResponse, error)
}

type wordCountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWordCountServiceClient(cc grpc.ClientConnInterface) WordCountServiceClient {
	return &wordCountServiceClient{cc}
}

func (c *wordCountServiceClient) CountWords(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*WordCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WordCountResponse)
	err := c.cc.Invoke(ctx, WordCountService_CountWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WordCountServiceServer is the server API for WordCountService service.
// All implementations must embed UnimplementedWordCountServiceServer
// for forward compatibility.
type WordCountServiceServer interface {
	CountWords(context.Context, *TextRequest) (*WordCountResponse, error)
	mustEmbedUnimplementedWordCountServiceServer()
}

// UnimplementedWordCountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWordCountServiceServer struct{}

func (UnimplementedWordCountServiceServer) CountWords(context.Context, *TextRequest) (*WordCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountWords not implemented")
}
func (UnimplementedWordCountServiceServer) mustEmbedUnimplementedWordCountServiceServer() {}
func (UnimplementedWordCountServiceServer) testEmbeddedByValue()                          {}

// UnsafeWordCountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WordCountServiceServer will
// result in compilation errors.
type UnsafeWordCountServiceServer interface {
	mustEmbedUnimplementedWordCountServiceServer()
}

func RegisterWordCountServiceServer(s grpc.ServiceRegistrar, srv WordCountServiceServer) {
	// If the following call pancis, it indicates UnimplementedWordCountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WordCountService_ServiceDesc, srv)
}

func _WordCountService_CountWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WordCountServiceServer).CountWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WordCountService_CountWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WordCountServiceServer).CountWords(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WordCountService_ServiceDesc is the grpc.ServiceDesc for WordCountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WordCountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WordCountService",
	HandlerType: (*WordCountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountWords",
			Handler:    _WordCountService_CountWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wordcount.proto",
}
