# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13server_stream.proto\"\x1f\n\x0bNewsRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\" \n\x0cNewsHeadline\x12\x10\n\x08headline\x18\x01 \x01(\t2?\n\x0bNewsService\x12\x30\n\x0fStreamHeadlines\x12\x0c.NewsRequest\x1a\r.NewsHeadline0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWSREQUEST']._serialized_start=23
  _globals['_NEWSREQUEST']._serialized_end=54
  _globals['_NEWSHEADLINE']._serialized_start=56
  _globals['_NEWSHEADLINE']._serialized_end=88
  _globals['_NEWSSERVICE']._serialized_start=90
  _globals['_NEWSSERVICE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
